# 开发环境配置
server:
  port: 8033
spring:
  # 数据库连接配置
  datasource:
    # 初始化连接池个数
    initialSize: 3
    # 最大连接池个数
    maxActive: 50
    # 配置获取连接等待超时的时间，单位毫秒，缺省启用公平锁，并发效率会有所下降
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 60000
    url: jdbc:mysql://81.68.87.72:3306/heruistics?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=true
    username: heRuistics
    password: ByjzeAMTkyfvT28R

  #redis相关配置
  redis:
    host: 47.94.210.61
    port: 6379
    password: XA0PAgme1mfGP9qX
    pool:
      # 最大连接数（负值表示没有限制）
      max-active: 8
      # 最大阻塞等待时间（负值表示没有限制）
      max-wait: 1
      # 最大空闲链接
      max-idle: 8
      # 最小空闲链接
      min-idle: 0
    # 链接超时时间（毫秒）
    timeout: 0